### ISSUE TITLE
how about a second drop down menu of our choice

### ISSUE THREAD

**Issue by pickybl2020** [fthx/babar#31]
maybe not a "ba bar" specific question but ill ask anyway...

how about a 2nd drop menu like the "favourites" one with items of our choice? 
to avoid any confusion with the rest of the system could be "ba bar" only option with a user defined sub-/menu
e.g.  shortcuts/bookmarks/projects/files  from browser and other apps 

also adding the ability to add submenus on the clickable items themselves 

thank you for listening

**Comment by fthx** [comment]
This should be a nice menu, but that would be a looot of work because of all the different objects you want in.

This kind of menu could imo be useful if and only if it's easy to use, with drag and drop. But these objects to dnd are so different that I'm not feeling able to implement all the necessary code.
