### ISSUE TITLE
[Feature] Display windows title next to the icon

### ISSUE THREAD

**Issue by mbousq** [fthx/babar#34]
Hi. Thanks for all the work. Would it be possible to have the option to display the window title next to the icons ? Thx !

**Comment by fthx** [comment]
Do you want a full native app menu or just the title of the window (not app title)?

**Comment by mbousq** [comment]
Thanks for getting back to me. Just the title of the window next to the icon. Would help selecting while having multiple windows of the same app.

**Comment by fthx** [comment]
Hmm.
I understand now what you want but it won't fit the panel h-size, imho. I would have to truncate the titles too much, so they won't be useful. Maybe have you tried Windows List official extension?

You already have an instant tooltip to allow fast search through same app icons. For me, the only way to achieve your goal is to group windows by app. But that's not the way this extension work, partly because BaBar handles per-desktop windows icons.

I close this now. If you have an idea that can fit what you want and the panel size, feel free to reopen, of course!

**Comment by mbousq** [comment]
I see, actually the instant tooltip works very well :). Thanks you for this extension !

**Comment by titov-vv** [comment]
I would vote for this feature also. I disagree with statement that space isn't enough :)
But let's stick to the facts.
Reasons why I would like to have titles together with icons:
1. I don't know exact reason but sometimes gnome fails to display a correct icon (not only in your extention). With title it won't be a bit problem.
2. I may have several copies of the same application launched. And all of them will have the same icon.
Why I think space is enough: 
I undertand that someone may have dozens of apps opened on each workspace (like my friends who have 100+ tabs opened in firefox). But there are people like me also - for me it's faster to close and open app again, so I have 3-7 apps running at the moment. I use [Flippery Bottom Panel](https://extensions.gnome.org/extension/3/bottom-panel/) and with 4 apps it has ~50% of free space. At the same tiem BaBar Task Bar has about ~70% free space. This is why I think space should be enough.
How it might be done in a better way:
In BaBar Task Bar app icons are split between workspaces. I may propose to keep only icons for inactive workspace. But for acitve workspace it may be an icon+title. 
And of course there should be a switch to turn this behavior on/off - if someone prefer old behavior without titles.
If you still have doubts I may post some images to illustrate how it looks like :)
