### ISSUE TITLE
Horisontal workspaces, autostart and hotkeys 

### ISSUE THREAD

**Issue by stranger169** [fthx/babar#9]
First of all, thanks for the great extension. I want to ask to add some features.

1. Horisontal workspaces. For me it's much more logical then vertical workspaces.
2. Hotkeys for workspaces by numbers. Pretty much any modificators keys, but some fast way to switch workspaces nonlinearly.
3. Hotkey to fast change between two workspaces. It will wonderful for coding and testing. Just one key, preferably customizable to go back to last workspace.
4. Autostart application to workspaces. It can be last state or customizable by config, doesn't matter, just way to fast recreation of working setup.

I would be grateful if you consider including this features in the extension.

**Comment by fthx** [comment]
1. I won't do that because there is already the official Horizontal Workspaces extension that does the trick and GNOME 40 will use horizontal workspaces by default. I did not test GNOME 40 yet. An user told me this extension is working, except the app grid button (that has been deleted from GS 40).
2. See (3).
3. I won't do that because that's not the goal of this extension. I agree it could be handy to have some shortcuts but you can set almost that you want by editing GNOME Settings / Keyboard Shortcuts. There are shortcuts to set for moving directly to a numbered workspace. I don't know if there are some other extensions that do this. Anyway, it could be another extension's job; BaBar is not interfering with GS normal behaviour.
4. Just install https://extensions.gnome.org/extension/16/auto-move-windows and add your apps to GNOME autostart.

Sorry to not accepting all your queries but at least I hope I helped some!
:-)

**Comment by fthx** [comment]
Oh, please note that the upcoming v24 of BaBar does add arrows to move windows from a workspace to another (+hide dash/workspaces in overview options).
You can find it here or here:
https://extensions.gnome.org/review/download/22325.shell-extension.zip
I know it's no better than drag'n'drop, but I do what I can!

**Comment by stranger169** [comment]
Moving windows to next workspace already was in hotkeys. <Control><Shift><Alt>Down and <Super><Shift>Page_Down in org.gnome.desktop.wm.keybindings.
I'm set hotkeys for workspaces already, thanx for the hint. Tried  Super + number, but couldn't disable Unity shortcuts, so i'm set for Ctrl+Shift+number.
Horisontal workspaces i'm tried, but it has some incompatibility with UI, but i'll will wait for gnome 40, unfortunately ubuntu won't include it in 21.04 release, so probably it will be long wait.
Hotkey for last workspace extension exist, but not work at all. If it ever seems to you that this can be done, then I personally  will be very glad.

**Comment by fthx** [comment]
Yes moving windows through workspaces does already have shortcuts. BaBar make this available with icons, if wanted only.

I keep your shortcuts demands in mind for later.

**Comment by stranger169** [comment]
Thanx, i'll be grateful.
And one small thing more. After last update icons for workspaces dosn't include numbers, but "..." instead everywhere except clear workspace.

**Comment by fthx** [comment]
Hmm that's odd.
I did not change anything related to workspaces labels (buttons). I tried in my Fedora virtual machine but there's no problem, as in my main Ubuntu 20.04 system.
Please have a look on your side about your modifications and tell me if it persists.

**Comment by stranger169** [comment]
I'm tried to disable all extensions except Babar, it's don't change anything, but after rebooting my pc it all right. I'm enabled most of needed extensions and it works fine, so sorry for bother. If I can recreate a bug in the future, then I will definitely inform you.
